src/Entity/Card.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CardRepository")
 *
 */
class Card
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Le code du centre de ne peut pas être nul.")
     *
     */
    private $codeCenter=123;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Le code de la carte ne peut pas être nul.")
     */
    private $codeCard;

    /**
     * @ORM\Column(type="integer")
     */
    private $checksum;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $status = "libre";

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $number_of_games;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", mappedBy="card", cascade={"persist", "remove"})
     */
    private $user;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeCentre(): ?int
    {
        return $this->codeCenter;
    }

    public function setCodeCentre(int $code_center): self
    {
        $this->codeCenter = $code_center;

        return $this;
    }

    public function getCodeCard(): ?int
    {
        return $this->codeCard;
    }

    public function setCodeCard(int $codeCard): self
    {
        $this->codeCard = $codeCard;

        return $this;
    }

    public function getChecksum(): ?int
    {
        return $this->checksum;
    }

    public function setChecksum(int $checksum): self
    {
        $this->checksum = $checksum;

        return $this;
    }

    public function getStatus():?string
    {
        return $this->status;
    }



    public function setStatus($status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getNumberOfGames(): ?int
    {
        return $this->number_of_games;
    }

    public function setNumberOfGames(?int $number_of_games): self
    {
        $this->number_of_games = $number_of_games;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        // set (or unset) the owning side of the relation if necessary
        $newCard = $user === null ? null : $this;
        if ($newCard !== $user->getCard()) {
            $user->setCard($newCard);
        }

        return $this;
    }
}

src/Form/CardType.php
<?php

namespace App\Form;

use App\Entity\Card;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CardType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('codeCard')
            ->add('checksum')
            ->add('status')
            ->add('number_of_games')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Card::class,
        ]);
    }
}

src/Controller/Admin/CardController.php
<?php

namespace App\Controller\Admin;

use App\Card\CardWorkflowHandler;
use App\Service\CardGenerator;
use App\Entity\Card;
use App\Entity\User;
use App\Form\CardType;
use App\Repository\CardRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Workflow\Exception\LogicException;

/**
 * Class CardController
 * @package App\Controller\Admin
 * @Route("/card")
 */
class CardController extends AbstractController
{
    /**
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param CardRepository $cardRepository
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/")
     */
    public function index(Request $request, EntityManagerInterface $em, CardRepository $cardRepository,CardRepository $userRepository)
    {
        $cards = $cardRepository->findAll();
        $users = $userRepository->findAll();

        return $this->render('card/index.html.twig', [
            'cards' => $cards,
            'users' => $users,
        ]);
    }

    /**
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param CardGenerator $cardGenerator
     * @Route("/edit")
     */
    public function edit(Request $request, EntityManagerInterface $em,CardGenerator $cardGenerator,CardRepository $cardRepository)
    {

        $card = new Card();

        $cardCreate= $cardGenerator->generate(6);

        $card->setCodeCard($cardCreate['codeCarte']);
        $card->setChecksum($cardCreate['checkMod']);
        $this->addFlash('success', 'La carte est enregistrée.');

        //enregistrement en bdd
        $em->persist($card);
        $em->flush();
        $cards = $cardRepository->findAll();
        $cardLast=end($cards);
        return $this->render('/card/edit.html.twig',
            [
                'cardLast' => $cardLast
            ]
        );
    }

    /**
     * @param EntityManagerInterface $em
     * @param Card $card
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route("/delete/{id}")
     */
    public function delete(EntityManagerInterface $em, Card $card)
    {
        $em->remove($card);
        $em->flush();
        $this->addFlash(
            'success',
            'La carte est bien désactivée'
        );

        return $this->redirectToRoute(
            'app_admin_card_index'
        );
    }

    /**
     * @Route("/create", name="cards_created")
     */
    public function createCard()
    {
        $cards = $this->getDoctrine()
            ->getRepository(Card::class)
            ->findCardByState('create');

        return $this->render('card/index.html.twig', [
            'cards' => $cards
        ]);
    }
    /**
     * @Route("/free", name="cards_free")
     */
    public function freeCard()
    {
        $cards = $this->getDoctrine()
            ->getRepository(Card::class)
            ->findCardByState('free');

        return $this->render('card/index.html.twig', [
            'cards' => $cards
        ]);
    }

    /**
     * @Route("/affected", name="cards_affected")
     */
    public function affectedCard()
    {
        $cards = $this->getDoctrine()
            ->getRepository(Card::class)
            ->findCardByState('affected');

        return $this->render('card/index.html.twig', [
            'cards' => $cards
        ]);
    }

    /**
     * @Route("/pre_active", name="cards_pre_active")
     */
    public function preActiveCard()
    {
        $cards = $this->getDoctrine()
            ->getRepository(Card::class)
            ->findCardByState('pre_active');

        return $this->render('card/index.html.twig', [
            'cards' => $cards
        ]);
    }

    /**
     * @Route("/active", name="cards_active")
     */
    public function activeCard()
    {
        $cards = $this->getDoctrine()
            ->getRepository(Card::class)
            ->findCardByState('active');

        return $this->render('card/index.html.twig', [
            'cards' => $cards
        ]);
    }

    /**
     * @param $state
     * @param Card $card
     * @param Request $request
     * @param CardWorkflowHandler $cwh
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route("/workflow/{state}/{id}", name="card_workflow")
     */
    public function workflow($state, Card $card, Request $request, CardWorkflowHandler $cwh)
    {
        //traitement du workflow
        try{
            $cwh->handle($card, $state);

            //notification
            $this->addFlash('notice', 'La carte est transmise');
        }catch (LogicException $e){
            $this->addFlash('error', 'changement de status impossible');
        }


        return $this->redirectToRoute('app_admin_card_index');
    }


}

src/Controller/CardController.php
<?php

namespace App\Controller;

use App\Service\CardGenerator;
use App\Entity\Card;
use App\Form\CardType;
use App\Repository\CardRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;





/**
 * Class CardController
 * @package App\Controller
 * @Route("card")
 */
class CardController extends AbstractController
{

    /**
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param CardRepository $cardRepository
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/")
     */
    public function index(Request $request, EntityManagerInterface $em, CardRepository $cardRepository)
    {
        $cards = $cardRepository->findAll();

        return $this->render('card/index.html.twig', [
            'cards' => $cards,
        ]);
    }



    /**
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param CardGenerator $cardGenerator
     * @Route("/edit")
     */
    public function edit(Request $request, EntityManagerInterface $em,CardGenerator $cardGenerator,CardRepository $cardRepository)
    {
        /*
              if (is_null($id)) {//création
                  $card = new Card();
              } else {//modification
                  $card = $em->find(Card::class, $id);
                  //404 si l'id n'est pas en BDD
                  if (is_null($card)) {
                      throw new NotFoundHttpException();
                  }
              }
        */
        $card = new Card();
        // $form = $this->createForm(CardType::class, $card);
        //$form->handleRequest($request);
        // création du formulaire relié à la catégorie
        //$form = $this->createForm(CardType::class, $id);
        // le formulaire analyse la requête et fait le mapping
        // avec l'entité s'il a été soumis
        //$form->handleRequest($request);
        //var_dump($cardGenerator->generate(6, 9)['codeCarte']);
        //$form->get('codeCard')->setData($cardGenerator->generate(6, 9)['codeCarte']);
        //$form->get('checksum')->setData($cardGenerator->generate(6, 9)['checkMod']);
        $cardCreate= $cardGenerator->generate(6);
        // var_dump($cardCreate['codeCarte']);
        // var_dump($cardCreate['checkMod']);
        $card->setCodeCard($cardCreate['codeCarte']);
        $card->setChecksum($cardCreate['checkMod']);
        $this->addFlash('success', 'La carte est enregistrée.');
        //enregistrement en bdd
        $em->persist($card);
        $em->flush();
        $cards = $cardRepository->findAll();
        $cardLast=end($cards);
        return $this->render('/card/edit.html.twig',
            [
                'cardLast' => $cardLast
            ]
        );
    }


    /**
     * @param EntityManagerInterface $em
     * @param Card $card
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route("/delete/{id}")
     */
    public function delete(EntityManagerInterface $em, Card $card)
    {
        $em->remove($card);
        $em->flush();
        $this->addFlash(
            'success',
            'La carte est bien désactivée'
        );

        return $this->redirectToRoute(
            'app_card_index'
        );

    }

}

templates/card/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
<h1>Carte créée</h1>
<div class="example-wrapper">{{cardLast.codeCentre}}--{{cardLast.codeCard}}--{{cardLast.checksum}}</div>
<a href="{{ path('app_admin_card_index') }}"
   class="button btn-outline-secondary">
    Retour
</a>
    </div>

    {% endblock %}

templates/card/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - Joueurs/Cartes{% endblock %}

{% block body %}

    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }
    </style>

    <div class="example-wrapper">
        <br>
        <h1 class="title is-1 has-text-white">Cartes</h1>
        <br>

        <a href="{{ path('app_search_searchcard') }}"
           class="button is-light mb-3">
            Recherche une carte
        </a>

        <a href="{{ path('app_admin_card_edit') }}"
           class="button is-light mb-3">
            Ajouter une carte
        </a> <br> <br>

        <table class="table">
            <tr>
                <th>Code Centre</th>
                <th>Code carte</th>
                <th>Clé</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Statut</th>
                <th>Nombre de parties</th>
                <th width="250px"></th>
            </tr>
            {% for key,card in cards %}
                {% if card.user %}
                    <tr>
                        <td>{{ card.codeCentre }}</td>
                        <td>{{ card.codeCard }}</td>
                        <td>{{ card.checksum }}</td>
                        <td>{{ card.user.lastname }}</td>
                        <td>{{ card.user.firstname }}</td>
                        <td>{{ card.status }}</td>
                        <td>{{ card.numberOfGames }}</td>
                        <td>
                           {% if workflow_can(card, 'active') %}
                                <a href="{{ path('card_workflow', {'id': card.id,
                                'state' : 'active',
                                'redirect' : app.request('_route')}) }}"
                                   class="btn btn-primary">
                                    Activer
                                </a>
                               {% endif %}

                                {% elseif card.getStatus()=="active" %}
                                    <div style="color: green;">Activé</div>
                            {% else %}
                                {% if workflow_can(card, 'affected') %}
                                <a href="{{ path('card_workflow', {'id': card.id,
                                'state' : 'affected'}) }}"
                                   class="btn btn-primary">
                                    Attribué
                                </a>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{ path('app_admin_card_delete', {'id': card.id}) }}"
                               class="btn btn-danger">
                                Supprimer
                            </a>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            {% for key,card in cards %}
                    {% if card.user is null%}
                    <tr>
                         <td>{{ card.codeCentre }}</td>
                         <td>{{ card.codeCard }}</td>
                         <td>{{ card.checksum }}</td>
                         <td>- - -</td>
                         <td>- - -</td>
                         <td>{{ card.status }}</td>
                         <td>{{ card.numberOfGames }}</td>
                         <td>
                             {% if workflow_can(card, 'affected') %}
                                 <a href="{{ path('card_workflow', {'id': card.id,
                                     'state' : 'affected'}) }}"
                                    class="btn btn-primary">
                                     Attribué
                                 </a>
                             {% endif %}
                        <td>
                            <a href="{{ path('app_admin_card_delete', {'id': card.id}) }}"
                               class="btn btn-danger">
                                Supprimer
                            </a>
                        </td>
                     <tr>
                    {% endif %}
            {% endfor %}
                {% if cards is empty%}
            <tr>
                <td colspan="5" class="text-center">
                    Aucun résultat
                </td>
            </tr>
            {% endif %}
        </table>
    </div>

{% endblock %}

templates/card/requestcardactive.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activer la carte!!!{% endblock %}

{% block body %}
    <h1>Activer la carte</h1>
          {{ form_start(form) }}
    <table>
      <tr>
          <th>{{ form_row(form.keycenter) }}</th>
          <th>{{ form_row(form.keycard) }}</th>
          <th>{{ form_row(form.checksum) }}</th>
     </tr>
    </table>
        <div class="text-right">
            <button type="submit" class="btn btn-primary">
                Enregistrer
            </button>
        </div>
    {{ form_end(form) }}
    <a href="{{ path('app_index_index') }}"
       class="btn btn-outline-secondary">
        Retour
    </a>

{% endblock %}